/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CnpCalificariDTO } from './CnpCalificariDTO';
import {
    CnpCalificariDTOFromJSON,
    CnpCalificariDTOFromJSONTyped,
    CnpCalificariDTOToJSON,
} from './CnpCalificariDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface CnpCalificariDTORequestResponse
 */
export interface CnpCalificariDTORequestResponse {
    /**
     * 
     * @type {CnpCalificariDTO}
     * @memberof CnpCalificariDTORequestResponse
     */
    response: CnpCalificariDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof CnpCalificariDTORequestResponse
     */
    errorMessage: ErrorMessage;
}

/**
 * Check if a given object implements the CnpCalificariDTORequestResponse interface.
 */
export function instanceOfCnpCalificariDTORequestResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "response" in value;
    isInstance = isInstance && "errorMessage" in value;

    return isInstance;
}

export function CnpCalificariDTORequestResponseFromJSON(json: any): CnpCalificariDTORequestResponse {
    return CnpCalificariDTORequestResponseFromJSONTyped(json, false);
}

export function CnpCalificariDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CnpCalificariDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': CnpCalificariDTOFromJSON(json['response']),
        'errorMessage': ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function CnpCalificariDTORequestResponseToJSON(value?: CnpCalificariDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': CnpCalificariDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

