/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CnpCalificariDTO } from './CnpCalificariDTO';
import {
    CnpCalificariDTOFromJSON,
    CnpCalificariDTOFromJSONTyped,
    CnpCalificariDTOToJSON,
} from './CnpCalificariDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface CnpCalificariDTORequestResponse
 */
export interface CnpCalificariDTORequestResponse {
    /**
     * 
     * @type {CnpCalificariDTO}
     * @memberof CnpCalificariDTORequestResponse
     */
    response: CnpCalificariDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof CnpCalificariDTORequestResponse
     */
    errorMessage: ErrorMessage;
}

/**
 * Check if a given object implements the CnpCalificariDTORequestResponse interface.
 */
export function instanceOfCnpCalificariDTORequestResponse(value: object): value is CnpCalificariDTORequestResponse {
    if (!('response' in value) || value['response'] === undefined) return false;
    if (!('errorMessage' in value) || value['errorMessage'] === undefined) return false;
    return true;
}

export function CnpCalificariDTORequestResponseFromJSON(json: any): CnpCalificariDTORequestResponse {
    return CnpCalificariDTORequestResponseFromJSONTyped(json, false);
}

export function CnpCalificariDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CnpCalificariDTORequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': CnpCalificariDTOFromJSON(json['response']),
        'errorMessage': ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function CnpCalificariDTORequestResponseToJSON(value?: CnpCalificariDTORequestResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'response': CnpCalificariDTOToJSON(value['response']),
        'errorMessage': ErrorMessageToJSON(value['errorMessage']),
    };
}

