/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CnpCalificariDTO } from './CnpCalificariDTO';
import {
    CnpCalificariDTOFromJSON,
    CnpCalificariDTOFromJSONTyped,
    CnpCalificariDTOToJSON,
} from './CnpCalificariDTO';

/**
 * 
 * @export
 * @interface CnpCalificariDTOPagedResponse
 */
export interface CnpCalificariDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof CnpCalificariDTOPagedResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof CnpCalificariDTOPagedResponse
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof CnpCalificariDTOPagedResponse
     */
    totalCount: number;
    /**
     * 
     * @type {Array<CnpCalificariDTO>}
     * @memberof CnpCalificariDTOPagedResponse
     */
    data: Array<CnpCalificariDTO>;
}

/**
 * Check if a given object implements the CnpCalificariDTOPagedResponse interface.
 */
export function instanceOfCnpCalificariDTOPagedResponse(value: object): value is CnpCalificariDTOPagedResponse {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CnpCalificariDTOPagedResponseFromJSON(json: any): CnpCalificariDTOPagedResponse {
    return CnpCalificariDTOPagedResponseFromJSONTyped(json, false);
}

export function CnpCalificariDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CnpCalificariDTOPagedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(CnpCalificariDTOFromJSON)),
    };
}

export function CnpCalificariDTOPagedResponseToJSON(value?: CnpCalificariDTOPagedResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'data': ((value['data'] as Array<any>).map(CnpCalificariDTOToJSON)),
    };
}

