/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CnpCalificariDTO
 */
export interface CnpCalificariDTO {
    /**
     * 
     * @type {string}
     * @memberof CnpCalificariDTO
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CnpCalificariDTO
     */
    idSolicitant: string;
    /**
     * 
     * @type {string}
     * @memberof CnpCalificariDTO
     */
    cnpSolicitant: string;
    /**
     * 
     * @type {string}
     * @memberof CnpCalificariDTO
     */
    idCor: string;
}

/**
 * Check if a given object implements the CnpCalificariDTO interface.
 */
export function instanceOfCnpCalificariDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "idSolicitant" in value;
    isInstance = isInstance && "cnpSolicitant" in value;
    isInstance = isInstance && "idCor" in value;

    return isInstance;
}

export function CnpCalificariDTOFromJSON(json: any): CnpCalificariDTO {
    return CnpCalificariDTOFromJSONTyped(json, false);
}

export function CnpCalificariDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CnpCalificariDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'idSolicitant': json['idSolicitant'],
        'cnpSolicitant': json['cnpSolicitant'],
        'idCor': json['idCor'],
    };
}

export function CnpCalificariDTOToJSON(value?: CnpCalificariDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'idSolicitant': value.idSolicitant,
        'cnpSolicitant': value.cnpSolicitant,
        'idCor': value.idCor,
    };
}

