/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CnpCalificariDTO
 */
export interface CnpCalificariDTO {
    /**
     * 
     * @type {string}
     * @memberof CnpCalificariDTO
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CnpCalificariDTO
     */
    idSolicitant: string;
    /**
     * 
     * @type {string}
     * @memberof CnpCalificariDTO
     */
    cnpSolicitant: string;
    /**
     * 
     * @type {string}
     * @memberof CnpCalificariDTO
     */
    idCor: string;
}

/**
 * Check if a given object implements the CnpCalificariDTO interface.
 */
export function instanceOfCnpCalificariDTO(value: object): value is CnpCalificariDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('idSolicitant' in value) || value['idSolicitant'] === undefined) return false;
    if (!('cnpSolicitant' in value) || value['cnpSolicitant'] === undefined) return false;
    if (!('idCor' in value) || value['idCor'] === undefined) return false;
    return true;
}

export function CnpCalificariDTOFromJSON(json: any): CnpCalificariDTO {
    return CnpCalificariDTOFromJSONTyped(json, false);
}

export function CnpCalificariDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CnpCalificariDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'idSolicitant': json['idSolicitant'],
        'cnpSolicitant': json['cnpSolicitant'],
        'idCor': json['idCor'],
    };
}

export function CnpCalificariDTOToJSON(value?: CnpCalificariDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'idSolicitant': value['idSolicitant'],
        'cnpSolicitant': value['cnpSolicitant'],
        'idCor': value['idCor'],
    };
}

