/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CnpCalificariDTO } from './CnpCalificariDTO';
import {
    CnpCalificariDTOFromJSON,
    CnpCalificariDTOFromJSONTyped,
    CnpCalificariDTOToJSON,
} from './CnpCalificariDTO';

/**
 * 
 * @export
 * @interface CnpCalificariDTOPagedResponse
 */
export interface CnpCalificariDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof CnpCalificariDTOPagedResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof CnpCalificariDTOPagedResponse
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof CnpCalificariDTOPagedResponse
     */
    totalCount: number;
    /**
     * 
     * @type {Array<CnpCalificariDTO>}
     * @memberof CnpCalificariDTOPagedResponse
     */
    data: Array<CnpCalificariDTO>;
}

/**
 * Check if a given object implements the CnpCalificariDTOPagedResponse interface.
 */
export function instanceOfCnpCalificariDTOPagedResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "page" in value;
    isInstance = isInstance && "pageSize" in value;
    isInstance = isInstance && "totalCount" in value;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function CnpCalificariDTOPagedResponseFromJSON(json: any): CnpCalificariDTOPagedResponse {
    return CnpCalificariDTOPagedResponseFromJSONTyped(json, false);
}

export function CnpCalificariDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CnpCalificariDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(CnpCalificariDTOFromJSON)),
    };
}

export function CnpCalificariDTOPagedResponseToJSON(value?: CnpCalificariDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': ((value.data as Array<any>).map(CnpCalificariDTOToJSON)),
    };
}

