/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CnpCalificariDTOPagedResponse } from './CnpCalificariDTOPagedResponse';
import {
    CnpCalificariDTOPagedResponseFromJSON,
    CnpCalificariDTOPagedResponseFromJSONTyped,
    CnpCalificariDTOPagedResponseToJSON,
} from './CnpCalificariDTOPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface CnpCalificariDTOPagedResponseRequestResponse
 */
export interface CnpCalificariDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {CnpCalificariDTOPagedResponse}
     * @memberof CnpCalificariDTOPagedResponseRequestResponse
     */
    response: CnpCalificariDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof CnpCalificariDTOPagedResponseRequestResponse
     */
    errorMessage: ErrorMessage;
}

/**
 * Check if a given object implements the CnpCalificariDTOPagedResponseRequestResponse interface.
 */
export function instanceOfCnpCalificariDTOPagedResponseRequestResponse(value: object): value is CnpCalificariDTOPagedResponseRequestResponse {
    if (!('response' in value) || value['response'] === undefined) return false;
    if (!('errorMessage' in value) || value['errorMessage'] === undefined) return false;
    return true;
}

export function CnpCalificariDTOPagedResponseRequestResponseFromJSON(json: any): CnpCalificariDTOPagedResponseRequestResponse {
    return CnpCalificariDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function CnpCalificariDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CnpCalificariDTOPagedResponseRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': CnpCalificariDTOPagedResponseFromJSON(json['response']),
        'errorMessage': ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function CnpCalificariDTOPagedResponseRequestResponseToJSON(value?: CnpCalificariDTOPagedResponseRequestResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'response': CnpCalificariDTOPagedResponseToJSON(value['response']),
        'errorMessage': ErrorMessageToJSON(value['errorMessage']),
    };
}

