/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CnpCalificariAddDTO
 */
export interface CnpCalificariAddDTO {
    /**
     * 
     * @type {string}
     * @memberof CnpCalificariAddDTO
     */
    idSolicitant: string;
    /**
     * 
     * @type {string}
     * @memberof CnpCalificariAddDTO
     */
    cnpSolicitant: string;
    /**
     * 
     * @type {string}
     * @memberof CnpCalificariAddDTO
     */
    idCor: string;
}

/**
 * Check if a given object implements the CnpCalificariAddDTO interface.
 */
export function instanceOfCnpCalificariAddDTO(value: object): value is CnpCalificariAddDTO {
    if (!('idSolicitant' in value) || value['idSolicitant'] === undefined) return false;
    if (!('cnpSolicitant' in value) || value['cnpSolicitant'] === undefined) return false;
    if (!('idCor' in value) || value['idCor'] === undefined) return false;
    return true;
}

export function CnpCalificariAddDTOFromJSON(json: any): CnpCalificariAddDTO {
    return CnpCalificariAddDTOFromJSONTyped(json, false);
}

export function CnpCalificariAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CnpCalificariAddDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'idSolicitant': json['idSolicitant'],
        'cnpSolicitant': json['cnpSolicitant'],
        'idCor': json['idCor'],
    };
}

export function CnpCalificariAddDTOToJSON(value?: CnpCalificariAddDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'idSolicitant': value['idSolicitant'],
        'cnpSolicitant': value['cnpSolicitant'],
        'idCor': value['idCor'],
    };
}

