/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CnpStudiiDTO } from './CnpStudiiDTO';
import {
    CnpStudiiDTOFromJSON,
    CnpStudiiDTOFromJSONTyped,
    CnpStudiiDTOToJSON,
} from './CnpStudiiDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface CnpStudiiDTORequestResponse
 */
export interface CnpStudiiDTORequestResponse {
    /**
     * 
     * @type {CnpStudiiDTO}
     * @memberof CnpStudiiDTORequestResponse
     */
    response: CnpStudiiDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof CnpStudiiDTORequestResponse
     */
    errorMessage: ErrorMessage;
}

/**
 * Check if a given object implements the CnpStudiiDTORequestResponse interface.
 */
export function instanceOfCnpStudiiDTORequestResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "response" in value;
    isInstance = isInstance && "errorMessage" in value;

    return isInstance;
}

export function CnpStudiiDTORequestResponseFromJSON(json: any): CnpStudiiDTORequestResponse {
    return CnpStudiiDTORequestResponseFromJSONTyped(json, false);
}

export function CnpStudiiDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CnpStudiiDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': CnpStudiiDTOFromJSON(json['response']),
        'errorMessage': ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function CnpStudiiDTORequestResponseToJSON(value?: CnpStudiiDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': CnpStudiiDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

