/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CnpStudiiDTO } from './CnpStudiiDTO';
import {
    CnpStudiiDTOFromJSON,
    CnpStudiiDTOFromJSONTyped,
    CnpStudiiDTOToJSON,
} from './CnpStudiiDTO';

/**
 * 
 * @export
 * @interface CnpStudiiDTOPagedResponse
 */
export interface CnpStudiiDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof CnpStudiiDTOPagedResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof CnpStudiiDTOPagedResponse
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof CnpStudiiDTOPagedResponse
     */
    totalCount: number;
    /**
     * 
     * @type {Array<CnpStudiiDTO>}
     * @memberof CnpStudiiDTOPagedResponse
     */
    data: Array<CnpStudiiDTO>;
}

/**
 * Check if a given object implements the CnpStudiiDTOPagedResponse interface.
 */
export function instanceOfCnpStudiiDTOPagedResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "page" in value;
    isInstance = isInstance && "pageSize" in value;
    isInstance = isInstance && "totalCount" in value;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function CnpStudiiDTOPagedResponseFromJSON(json: any): CnpStudiiDTOPagedResponse {
    return CnpStudiiDTOPagedResponseFromJSONTyped(json, false);
}

export function CnpStudiiDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CnpStudiiDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(CnpStudiiDTOFromJSON)),
    };
}

export function CnpStudiiDTOPagedResponseToJSON(value?: CnpStudiiDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': ((value.data as Array<any>).map(CnpStudiiDTOToJSON)),
    };
}

