/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CnpStudiiDTO } from './CnpStudiiDTO';
import {
    CnpStudiiDTOFromJSON,
    CnpStudiiDTOFromJSONTyped,
    CnpStudiiDTOToJSON,
} from './CnpStudiiDTO';

/**
 * 
 * @export
 * @interface CnpStudiiDTOPagedResponse
 */
export interface CnpStudiiDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof CnpStudiiDTOPagedResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof CnpStudiiDTOPagedResponse
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof CnpStudiiDTOPagedResponse
     */
    totalCount: number;
    /**
     * 
     * @type {Array<CnpStudiiDTO>}
     * @memberof CnpStudiiDTOPagedResponse
     */
    data: Array<CnpStudiiDTO>;
}

/**
 * Check if a given object implements the CnpStudiiDTOPagedResponse interface.
 */
export function instanceOfCnpStudiiDTOPagedResponse(value: object): value is CnpStudiiDTOPagedResponse {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CnpStudiiDTOPagedResponseFromJSON(json: any): CnpStudiiDTOPagedResponse {
    return CnpStudiiDTOPagedResponseFromJSONTyped(json, false);
}

export function CnpStudiiDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CnpStudiiDTOPagedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(CnpStudiiDTOFromJSON)),
    };
}

export function CnpStudiiDTOPagedResponseToJSON(value?: CnpStudiiDTOPagedResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'data': ((value['data'] as Array<any>).map(CnpStudiiDTOToJSON)),
    };
}

