/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CnpStudiiAddDTO
 */
export interface CnpStudiiAddDTO {
    /**
     * 
     * @type {string}
     * @memberof CnpStudiiAddDTO
     */
    idSolicitant: string;
    /**
     * 
     * @type {string}
     * @memberof CnpStudiiAddDTO
     */
    cnpSolicitant: string;
    /**
     * 
     * @type {string}
     * @memberof CnpStudiiAddDTO
     */
    idStudii: string;
}

/**
 * Check if a given object implements the CnpStudiiAddDTO interface.
 */
export function instanceOfCnpStudiiAddDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "idSolicitant" in value;
    isInstance = isInstance && "cnpSolicitant" in value;
    isInstance = isInstance && "idStudii" in value;

    return isInstance;
}

export function CnpStudiiAddDTOFromJSON(json: any): CnpStudiiAddDTO {
    return CnpStudiiAddDTOFromJSONTyped(json, false);
}

export function CnpStudiiAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CnpStudiiAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'idSolicitant': json['idSolicitant'],
        'cnpSolicitant': json['cnpSolicitant'],
        'idStudii': json['idStudii'],
    };
}

export function CnpStudiiAddDTOToJSON(value?: CnpStudiiAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'idSolicitant': value.idSolicitant,
        'cnpSolicitant': value.cnpSolicitant,
        'idStudii': value.idStudii,
    };
}

