/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CnpStudiiDTO
 */
export interface CnpStudiiDTO {
    /**
     * 
     * @type {string}
     * @memberof CnpStudiiDTO
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CnpStudiiDTO
     */
    idSolicitant: string;
    /**
     * 
     * @type {string}
     * @memberof CnpStudiiDTO
     */
    cnpSolicitant: string;
    /**
     * 
     * @type {string}
     * @memberof CnpStudiiDTO
     */
    idStudii: string;
}

/**
 * Check if a given object implements the CnpStudiiDTO interface.
 */
export function instanceOfCnpStudiiDTO(value: object): value is CnpStudiiDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('idSolicitant' in value) || value['idSolicitant'] === undefined) return false;
    if (!('cnpSolicitant' in value) || value['cnpSolicitant'] === undefined) return false;
    if (!('idStudii' in value) || value['idStudii'] === undefined) return false;
    return true;
}

export function CnpStudiiDTOFromJSON(json: any): CnpStudiiDTO {
    return CnpStudiiDTOFromJSONTyped(json, false);
}

export function CnpStudiiDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CnpStudiiDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'idSolicitant': json['idSolicitant'],
        'cnpSolicitant': json['cnpSolicitant'],
        'idStudii': json['idStudii'],
    };
}

export function CnpStudiiDTOToJSON(value?: CnpStudiiDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'idSolicitant': value['idSolicitant'],
        'cnpSolicitant': value['cnpSolicitant'],
        'idStudii': value['idStudii'],
    };
}

