/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CorAddDTO
 */
export interface CorAddDTO {
    /**
     * 
     * @type {string}
     * @memberof CorAddDTO
     */
    codCor: string;
    /**
     * 
     * @type {string}
     * @memberof CorAddDTO
     */
    meserie: string;
}

/**
 * Check if a given object implements the CorAddDTO interface.
 */
export function instanceOfCorAddDTO(value: object): value is CorAddDTO {
    if (!('codCor' in value) || value['codCor'] === undefined) return false;
    if (!('meserie' in value) || value['meserie'] === undefined) return false;
    return true;
}

export function CorAddDTOFromJSON(json: any): CorAddDTO {
    return CorAddDTOFromJSONTyped(json, false);
}

export function CorAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorAddDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'codCor': json['codCor'],
        'meserie': json['meserie'],
    };
}

export function CorAddDTOToJSON(value?: CorAddDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'codCor': value['codCor'],
        'meserie': value['meserie'],
    };
}

