/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CorAddDTO
 */
export interface CorAddDTO {
    /**
     * 
     * @type {string}
     * @memberof CorAddDTO
     */
    codCor: string;
    /**
     * 
     * @type {string}
     * @memberof CorAddDTO
     */
    meserie: string;
}

/**
 * Check if a given object implements the CorAddDTO interface.
 */
export function instanceOfCorAddDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "codCor" in value;
    isInstance = isInstance && "meserie" in value;

    return isInstance;
}

export function CorAddDTOFromJSON(json: any): CorAddDTO {
    return CorAddDTOFromJSONTyped(json, false);
}

export function CorAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'codCor': json['codCor'],
        'meserie': json['meserie'],
    };
}

export function CorAddDTOToJSON(value?: CorAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'codCor': value.codCor,
        'meserie': value.meserie,
    };
}

