/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CorDTO } from './CorDTO';
import {
    CorDTOFromJSON,
    CorDTOFromJSONTyped,
    CorDTOToJSON,
} from './CorDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface CorDTORequestResponse
 */
export interface CorDTORequestResponse {
    /**
     * 
     * @type {CorDTO}
     * @memberof CorDTORequestResponse
     */
    response: CorDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof CorDTORequestResponse
     */
    errorMessage: ErrorMessage;
}

/**
 * Check if a given object implements the CorDTORequestResponse interface.
 */
export function instanceOfCorDTORequestResponse(value: object): value is CorDTORequestResponse {
    if (!('response' in value) || value['response'] === undefined) return false;
    if (!('errorMessage' in value) || value['errorMessage'] === undefined) return false;
    return true;
}

export function CorDTORequestResponseFromJSON(json: any): CorDTORequestResponse {
    return CorDTORequestResponseFromJSONTyped(json, false);
}

export function CorDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorDTORequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': CorDTOFromJSON(json['response']),
        'errorMessage': ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function CorDTORequestResponseToJSON(value?: CorDTORequestResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'response': CorDTOToJSON(value['response']),
        'errorMessage': ErrorMessageToJSON(value['errorMessage']),
    };
}

