/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CorDTO } from './CorDTO';
import {
    CorDTOFromJSON,
    CorDTOFromJSONTyped,
    CorDTOToJSON,
} from './CorDTO';

/**
 * 
 * @export
 * @interface CorDTOPagedResponse
 */
export interface CorDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof CorDTOPagedResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof CorDTOPagedResponse
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof CorDTOPagedResponse
     */
    totalCount: number;
    /**
     * 
     * @type {Array<CorDTO>}
     * @memberof CorDTOPagedResponse
     */
    data: Array<CorDTO>;
}

/**
 * Check if a given object implements the CorDTOPagedResponse interface.
 */
export function instanceOfCorDTOPagedResponse(value: object): value is CorDTOPagedResponse {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CorDTOPagedResponseFromJSON(json: any): CorDTOPagedResponse {
    return CorDTOPagedResponseFromJSONTyped(json, false);
}

export function CorDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorDTOPagedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(CorDTOFromJSON)),
    };
}

export function CorDTOPagedResponseToJSON(value?: CorDTOPagedResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'data': ((value['data'] as Array<any>).map(CorDTOToJSON)),
    };
}

