/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CorDTO
 */
export interface CorDTO {
    /**
     * 
     * @type {string}
     * @memberof CorDTO
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CorDTO
     */
    codCor: string;
    /**
     * 
     * @type {string}
     * @memberof CorDTO
     */
    meserie: string;
}

/**
 * Check if a given object implements the CorDTO interface.
 */
export function instanceOfCorDTO(value: object): value is CorDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('codCor' in value) || value['codCor'] === undefined) return false;
    if (!('meserie' in value) || value['meserie'] === undefined) return false;
    return true;
}

export function CorDTOFromJSON(json: any): CorDTO {
    return CorDTOFromJSONTyped(json, false);
}

export function CorDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'codCor': json['codCor'],
        'meserie': json['meserie'],
    };
}

export function CorDTOToJSON(value?: CorDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'codCor': value['codCor'],
        'meserie': value['meserie'],
    };
}

