/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { DosarDTOPagedResponse } from './DosarDTOPagedResponse';
import {
    DosarDTOPagedResponseFromJSON,
    DosarDTOPagedResponseFromJSONTyped,
    DosarDTOPagedResponseToJSON,
} from './DosarDTOPagedResponse';

/**
 * 
 * @export
 * @interface DosarDTOPagedResponseRequestResponse
 */
export interface DosarDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {DosarDTOPagedResponse}
     * @memberof DosarDTOPagedResponseRequestResponse
     */
    response: DosarDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof DosarDTOPagedResponseRequestResponse
     */
    errorMessage: ErrorMessage;
}

/**
 * Check if a given object implements the DosarDTOPagedResponseRequestResponse interface.
 */
export function instanceOfDosarDTOPagedResponseRequestResponse(value: object): value is DosarDTOPagedResponseRequestResponse {
    if (!('response' in value) || value['response'] === undefined) return false;
    if (!('errorMessage' in value) || value['errorMessage'] === undefined) return false;
    return true;
}

export function DosarDTOPagedResponseRequestResponseFromJSON(json: any): DosarDTOPagedResponseRequestResponse {
    return DosarDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function DosarDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DosarDTOPagedResponseRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': DosarDTOPagedResponseFromJSON(json['response']),
        'errorMessage': ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function DosarDTOPagedResponseRequestResponseToJSON(value?: DosarDTOPagedResponseRequestResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'response': DosarDTOPagedResponseToJSON(value['response']),
        'errorMessage': ErrorMessageToJSON(value['errorMessage']),
    };
}

