/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DosarRepartitiiAddDTO
 */
export interface DosarRepartitiiAddDTO {
    /**
     * 
     * @type {string}
     * @memberof DosarRepartitiiAddDTO
     */
    idDosar: string;
    /**
     * 
     * @type {string}
     * @memberof DosarRepartitiiAddDTO
     */
    idRepartitie: string;
}

/**
 * Check if a given object implements the DosarRepartitiiAddDTO interface.
 */
export function instanceOfDosarRepartitiiAddDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "idDosar" in value;
    isInstance = isInstance && "idRepartitie" in value;

    return isInstance;
}

export function DosarRepartitiiAddDTOFromJSON(json: any): DosarRepartitiiAddDTO {
    return DosarRepartitiiAddDTOFromJSONTyped(json, false);
}

export function DosarRepartitiiAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DosarRepartitiiAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'idDosar': json['idDosar'],
        'idRepartitie': json['idRepartitie'],
    };
}

export function DosarRepartitiiAddDTOToJSON(value?: DosarRepartitiiAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'idDosar': value.idDosar,
        'idRepartitie': value.idRepartitie,
    };
}

