/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DosarDTOPagedResponse } from './DosarDTOPagedResponse';
import {
    DosarDTOPagedResponseFromJSON,
    DosarDTOPagedResponseFromJSONTyped,
    DosarDTOPagedResponseToJSON,
} from './DosarDTOPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface DosarDTOPagedResponseRequestResponse
 */
export interface DosarDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {DosarDTOPagedResponse}
     * @memberof DosarDTOPagedResponseRequestResponse
     */
    response: DosarDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof DosarDTOPagedResponseRequestResponse
     */
    errorMessage: ErrorMessage;
}

/**
 * Check if a given object implements the DosarDTOPagedResponseRequestResponse interface.
 */
export function instanceOfDosarDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "response" in value;
    isInstance = isInstance && "errorMessage" in value;

    return isInstance;
}

export function DosarDTOPagedResponseRequestResponseFromJSON(json: any): DosarDTOPagedResponseRequestResponse {
    return DosarDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function DosarDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DosarDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': DosarDTOPagedResponseFromJSON(json['response']),
        'errorMessage': ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function DosarDTOPagedResponseRequestResponseToJSON(value?: DosarDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': DosarDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

