/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DosarDTO } from './DosarDTO';
import {
    DosarDTOFromJSON,
    DosarDTOFromJSONTyped,
    DosarDTOToJSON,
} from './DosarDTO';

/**
 * 
 * @export
 * @interface DosarDTOPagedResponse
 */
export interface DosarDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof DosarDTOPagedResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof DosarDTOPagedResponse
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof DosarDTOPagedResponse
     */
    totalCount: number;
    /**
     * 
     * @type {Array<DosarDTO>}
     * @memberof DosarDTOPagedResponse
     */
    data: Array<DosarDTO>;
}

/**
 * Check if a given object implements the DosarDTOPagedResponse interface.
 */
export function instanceOfDosarDTOPagedResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "page" in value;
    isInstance = isInstance && "pageSize" in value;
    isInstance = isInstance && "totalCount" in value;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function DosarDTOPagedResponseFromJSON(json: any): DosarDTOPagedResponse {
    return DosarDTOPagedResponseFromJSONTyped(json, false);
}

export function DosarDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DosarDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(DosarDTOFromJSON)),
    };
}

export function DosarDTOPagedResponseToJSON(value?: DosarDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': ((value.data as Array<any>).map(DosarDTOToJSON)),
    };
}

