/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DosarStareEnum = {
    Activ: 'Activ',
    Incetat: 'Incetat'
} as const;
export type DosarStareEnum = typeof DosarStareEnum[keyof typeof DosarStareEnum];


export function DosarStareEnumFromJSON(json: any): DosarStareEnum {
    return DosarStareEnumFromJSONTyped(json, false);
}

export function DosarStareEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): DosarStareEnum {
    return json as DosarStareEnum;
}

export function DosarStareEnumToJSON(value?: DosarStareEnum | null): any {
    return value as any;
}

