/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DosarRepartitiiDTO } from './DosarRepartitiiDTO';
import {
    DosarRepartitiiDTOFromJSON,
    DosarRepartitiiDTOFromJSONTyped,
    DosarRepartitiiDTOToJSON,
} from './DosarRepartitiiDTO';

/**
 * 
 * @export
 * @interface DosarRepartitiiDTOPagedResponse
 */
export interface DosarRepartitiiDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof DosarRepartitiiDTOPagedResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof DosarRepartitiiDTOPagedResponse
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof DosarRepartitiiDTOPagedResponse
     */
    totalCount: number;
    /**
     * 
     * @type {Array<DosarRepartitiiDTO>}
     * @memberof DosarRepartitiiDTOPagedResponse
     */
    data: Array<DosarRepartitiiDTO>;
}

/**
 * Check if a given object implements the DosarRepartitiiDTOPagedResponse interface.
 */
export function instanceOfDosarRepartitiiDTOPagedResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "page" in value;
    isInstance = isInstance && "pageSize" in value;
    isInstance = isInstance && "totalCount" in value;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function DosarRepartitiiDTOPagedResponseFromJSON(json: any): DosarRepartitiiDTOPagedResponse {
    return DosarRepartitiiDTOPagedResponseFromJSONTyped(json, false);
}

export function DosarRepartitiiDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DosarRepartitiiDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(DosarRepartitiiDTOFromJSON)),
    };
}

export function DosarRepartitiiDTOPagedResponseToJSON(value?: DosarRepartitiiDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': ((value.data as Array<any>).map(DosarRepartitiiDTOToJSON)),
    };
}

