/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DosarUpdateDTO
 */
export interface DosarUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof DosarUpdateDTO
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof DosarUpdateDTO
     */
    dataDosar: Date;
    /**
     * 
     * @type {string}
     * @memberof DosarUpdateDTO
     */
    cnpSolicitant?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof DosarUpdateDTO
     */
    deLa: Date;
    /**
     * 
     * @type {Date}
     * @memberof DosarUpdateDTO
     */
    panaLa: Date;
}

/**
 * Check if a given object implements the DosarUpdateDTO interface.
 */
export function instanceOfDosarUpdateDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "dataDosar" in value;
    isInstance = isInstance && "deLa" in value;
    isInstance = isInstance && "panaLa" in value;

    return isInstance;
}

export function DosarUpdateDTOFromJSON(json: any): DosarUpdateDTO {
    return DosarUpdateDTOFromJSONTyped(json, false);
}

export function DosarUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DosarUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'dataDosar': (new Date(json['dataDosar'])),
        'cnpSolicitant': !exists(json, 'cnpSolicitant') ? undefined : json['cnpSolicitant'],
        'deLa': (new Date(json['deLa'])),
        'panaLa': (new Date(json['panaLa'])),
    };
}

export function DosarUpdateDTOToJSON(value?: DosarUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'dataDosar': (value.dataDosar.toISOString()),
        'cnpSolicitant': value.cnpSolicitant,
        'deLa': (value.deLa.toISOString()),
        'panaLa': (value.panaLa.toISOString()),
    };
}

