/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DosarRepartitiiDTOPagedResponse } from './DosarRepartitiiDTOPagedResponse';
import {
    DosarRepartitiiDTOPagedResponseFromJSON,
    DosarRepartitiiDTOPagedResponseFromJSONTyped,
    DosarRepartitiiDTOPagedResponseToJSON,
} from './DosarRepartitiiDTOPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface DosarRepartitiiDTOPagedResponseRequestResponse
 */
export interface DosarRepartitiiDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {DosarRepartitiiDTOPagedResponse}
     * @memberof DosarRepartitiiDTOPagedResponseRequestResponse
     */
    response: DosarRepartitiiDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof DosarRepartitiiDTOPagedResponseRequestResponse
     */
    errorMessage: ErrorMessage;
}

/**
 * Check if a given object implements the DosarRepartitiiDTOPagedResponseRequestResponse interface.
 */
export function instanceOfDosarRepartitiiDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "response" in value;
    isInstance = isInstance && "errorMessage" in value;

    return isInstance;
}

export function DosarRepartitiiDTOPagedResponseRequestResponseFromJSON(json: any): DosarRepartitiiDTOPagedResponseRequestResponse {
    return DosarRepartitiiDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function DosarRepartitiiDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DosarRepartitiiDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': DosarRepartitiiDTOPagedResponseFromJSON(json['response']),
        'errorMessage': ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function DosarRepartitiiDTOPagedResponseRequestResponseToJSON(value?: DosarRepartitiiDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': DosarRepartitiiDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

