/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DosarRepartitiiDTO } from './DosarRepartitiiDTO';
import {
    DosarRepartitiiDTOFromJSON,
    DosarRepartitiiDTOFromJSONTyped,
    DosarRepartitiiDTOToJSON,
} from './DosarRepartitiiDTO';

/**
 * 
 * @export
 * @interface DosarRepartitiiDTOPagedResponse
 */
export interface DosarRepartitiiDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof DosarRepartitiiDTOPagedResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof DosarRepartitiiDTOPagedResponse
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof DosarRepartitiiDTOPagedResponse
     */
    totalCount: number;
    /**
     * 
     * @type {Array<DosarRepartitiiDTO>}
     * @memberof DosarRepartitiiDTOPagedResponse
     */
    data: Array<DosarRepartitiiDTO>;
}

/**
 * Check if a given object implements the DosarRepartitiiDTOPagedResponse interface.
 */
export function instanceOfDosarRepartitiiDTOPagedResponse(value: object): value is DosarRepartitiiDTOPagedResponse {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function DosarRepartitiiDTOPagedResponseFromJSON(json: any): DosarRepartitiiDTOPagedResponse {
    return DosarRepartitiiDTOPagedResponseFromJSONTyped(json, false);
}

export function DosarRepartitiiDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DosarRepartitiiDTOPagedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(DosarRepartitiiDTOFromJSON)),
    };
}

export function DosarRepartitiiDTOPagedResponseToJSON(value?: DosarRepartitiiDTOPagedResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'data': ((value['data'] as Array<any>).map(DosarRepartitiiDTOToJSON)),
    };
}

