/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DosarDTO } from './DosarDTO';
import {
    DosarDTOFromJSON,
    DosarDTOFromJSONTyped,
    DosarDTOToJSON,
} from './DosarDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface DosarDTORequestResponse
 */
export interface DosarDTORequestResponse {
    /**
     * 
     * @type {DosarDTO}
     * @memberof DosarDTORequestResponse
     */
    response: DosarDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof DosarDTORequestResponse
     */
    errorMessage: ErrorMessage;
}

/**
 * Check if a given object implements the DosarDTORequestResponse interface.
 */
export function instanceOfDosarDTORequestResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "response" in value;
    isInstance = isInstance && "errorMessage" in value;

    return isInstance;
}

export function DosarDTORequestResponseFromJSON(json: any): DosarDTORequestResponse {
    return DosarDTORequestResponseFromJSONTyped(json, false);
}

export function DosarDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DosarDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': DosarDTOFromJSON(json['response']),
        'errorMessage': ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function DosarDTORequestResponseToJSON(value?: DosarDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': DosarDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

