/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DosarRepartitiiDTOPagedResponse } from './DosarRepartitiiDTOPagedResponse';
import {
    DosarRepartitiiDTOPagedResponseFromJSON,
    DosarRepartitiiDTOPagedResponseFromJSONTyped,
    DosarRepartitiiDTOPagedResponseToJSON,
} from './DosarRepartitiiDTOPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface DosarRepartitiiDTOPagedResponseRequestResponse
 */
export interface DosarRepartitiiDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {DosarRepartitiiDTOPagedResponse}
     * @memberof DosarRepartitiiDTOPagedResponseRequestResponse
     */
    response: DosarRepartitiiDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof DosarRepartitiiDTOPagedResponseRequestResponse
     */
    errorMessage: ErrorMessage;
}

/**
 * Check if a given object implements the DosarRepartitiiDTOPagedResponseRequestResponse interface.
 */
export function instanceOfDosarRepartitiiDTOPagedResponseRequestResponse(value: object): value is DosarRepartitiiDTOPagedResponseRequestResponse {
    if (!('response' in value) || value['response'] === undefined) return false;
    if (!('errorMessage' in value) || value['errorMessage'] === undefined) return false;
    return true;
}

export function DosarRepartitiiDTOPagedResponseRequestResponseFromJSON(json: any): DosarRepartitiiDTOPagedResponseRequestResponse {
    return DosarRepartitiiDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function DosarRepartitiiDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DosarRepartitiiDTOPagedResponseRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': DosarRepartitiiDTOPagedResponseFromJSON(json['response']),
        'errorMessage': ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function DosarRepartitiiDTOPagedResponseRequestResponseToJSON(value?: DosarRepartitiiDTOPagedResponseRequestResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'response': DosarRepartitiiDTOPagedResponseToJSON(value['response']),
        'errorMessage': ErrorMessageToJSON(value['errorMessage']),
    };
}

