/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DosarRepartitiiDTO } from './DosarRepartitiiDTO';
import {
    DosarRepartitiiDTOFromJSON,
    DosarRepartitiiDTOFromJSONTyped,
    DosarRepartitiiDTOToJSON,
} from './DosarRepartitiiDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface DosarRepartitiiDTORequestResponse
 */
export interface DosarRepartitiiDTORequestResponse {
    /**
     * 
     * @type {DosarRepartitiiDTO}
     * @memberof DosarRepartitiiDTORequestResponse
     */
    response: DosarRepartitiiDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof DosarRepartitiiDTORequestResponse
     */
    errorMessage: ErrorMessage;
}

/**
 * Check if a given object implements the DosarRepartitiiDTORequestResponse interface.
 */
export function instanceOfDosarRepartitiiDTORequestResponse(value: object): value is DosarRepartitiiDTORequestResponse {
    if (!('response' in value) || value['response'] === undefined) return false;
    if (!('errorMessage' in value) || value['errorMessage'] === undefined) return false;
    return true;
}

export function DosarRepartitiiDTORequestResponseFromJSON(json: any): DosarRepartitiiDTORequestResponse {
    return DosarRepartitiiDTORequestResponseFromJSONTyped(json, false);
}

export function DosarRepartitiiDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DosarRepartitiiDTORequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': DosarRepartitiiDTOFromJSON(json['response']),
        'errorMessage': ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function DosarRepartitiiDTORequestResponseToJSON(value?: DosarRepartitiiDTORequestResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'response': DosarRepartitiiDTOToJSON(value['response']),
        'errorMessage': ErrorMessageToJSON(value['errorMessage']),
    };
}

