/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DosarStareEnum } from './DosarStareEnum';
import {
    DosarStareEnumFromJSON,
    DosarStareEnumFromJSONTyped,
    DosarStareEnumToJSON,
} from './DosarStareEnum';

/**
 * 
 * @export
 * @interface DosarDTO
 */
export interface DosarDTO {
    /**
     * 
     * @type {string}
     * @memberof DosarDTO
     */
    idSolicitant: string;
    /**
     * 
     * @type {Date}
     * @memberof DosarDTO
     */
    dataDosar: Date;
    /**
     * 
     * @type {string}
     * @memberof DosarDTO
     */
    cnpSolicitant?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof DosarDTO
     */
    deLa: Date;
    /**
     * 
     * @type {Date}
     * @memberof DosarDTO
     */
    panaLa: Date;
    /**
     * 
     * @type {DosarStareEnum}
     * @memberof DosarDTO
     */
    stare: DosarStareEnum;
}

/**
 * Check if a given object implements the DosarDTO interface.
 */
export function instanceOfDosarDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "idSolicitant" in value;
    isInstance = isInstance && "dataDosar" in value;
    isInstance = isInstance && "deLa" in value;
    isInstance = isInstance && "panaLa" in value;
    isInstance = isInstance && "stare" in value;

    return isInstance;
}

export function DosarDTOFromJSON(json: any): DosarDTO {
    return DosarDTOFromJSONTyped(json, false);
}

export function DosarDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DosarDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'idSolicitant': json['idSolicitant'],
        'dataDosar': (new Date(json['dataDosar'])),
        'cnpSolicitant': !exists(json, 'cnpSolicitant') ? undefined : json['cnpSolicitant'],
        'deLa': (new Date(json['deLa'])),
        'panaLa': (new Date(json['panaLa'])),
        'stare': DosarStareEnumFromJSON(json['stare']),
    };
}

export function DosarDTOToJSON(value?: DosarDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'idSolicitant': value.idSolicitant,
        'dataDosar': (value.dataDosar.toISOString()),
        'cnpSolicitant': value.cnpSolicitant,
        'deLa': (value.deLa.toISOString()),
        'panaLa': (value.panaLa.toISOString()),
        'stare': DosarStareEnumToJSON(value.stare),
    };
}

