/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DosarDTO } from './DosarDTO';
import {
    DosarDTOFromJSON,
    DosarDTOFromJSONTyped,
    DosarDTOToJSON,
} from './DosarDTO';

/**
 * 
 * @export
 * @interface DosarDTOPagedResponse
 */
export interface DosarDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof DosarDTOPagedResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof DosarDTOPagedResponse
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof DosarDTOPagedResponse
     */
    totalCount: number;
    /**
     * 
     * @type {Array<DosarDTO>}
     * @memberof DosarDTOPagedResponse
     */
    data: Array<DosarDTO>;
}

/**
 * Check if a given object implements the DosarDTOPagedResponse interface.
 */
export function instanceOfDosarDTOPagedResponse(value: object): value is DosarDTOPagedResponse {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function DosarDTOPagedResponseFromJSON(json: any): DosarDTOPagedResponse {
    return DosarDTOPagedResponseFromJSONTyped(json, false);
}

export function DosarDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DosarDTOPagedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(DosarDTOFromJSON)),
    };
}

export function DosarDTOPagedResponseToJSON(value?: DosarDTOPagedResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'data': ((value['data'] as Array<any>).map(DosarDTOToJSON)),
    };
}

