/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OlmStareEnum } from './OlmStareEnum';
import {
    OlmStareEnumFromJSON,
    OlmStareEnumFromJSONTyped,
    OlmStareEnumToJSON,
} from './OlmStareEnum';

/**
 * 
 * @export
 * @interface OlmDTO
 */
export interface OlmDTO {
    /**
     * 
     * @type {Date}
     * @memberof OlmDTO
     */
    dataOlm: Date;
    /**
     * 
     * @type {Date}
     * @memberof OlmDTO
     */
    dataOlmStart: Date;
    /**
     * 
     * @type {Date}
     * @memberof OlmDTO
     */
    dataOlmSfarsit: Date;
    /**
     * 
     * @type {string}
     * @memberof OlmDTO
     */
    agent: string;
    /**
     * 
     * @type {string}
     * @memberof OlmDTO
     */
    cuiFirma: string;
    /**
     * 
     * @type {string}
     * @memberof OlmDTO
     */
    idCor: string;
    /**
     * 
     * @type {string}
     * @memberof OlmDTO
     */
    adresaLocMunca: string;
    /**
     * 
     * @type {number}
     * @memberof OlmDTO
     */
    nrLocMunca: number;
    /**
     * 
     * @type {OlmStareEnum}
     * @memberof OlmDTO
     */
    stare: OlmStareEnum;
}

/**
 * Check if a given object implements the OlmDTO interface.
 */
export function instanceOfOlmDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "dataOlm" in value;
    isInstance = isInstance && "dataOlmStart" in value;
    isInstance = isInstance && "dataOlmSfarsit" in value;
    isInstance = isInstance && "agent" in value;
    isInstance = isInstance && "cuiFirma" in value;
    isInstance = isInstance && "idCor" in value;
    isInstance = isInstance && "adresaLocMunca" in value;
    isInstance = isInstance && "nrLocMunca" in value;
    isInstance = isInstance && "stare" in value;

    return isInstance;
}

export function OlmDTOFromJSON(json: any): OlmDTO {
    return OlmDTOFromJSONTyped(json, false);
}

export function OlmDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): OlmDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'dataOlm': (new Date(json['dataOlm'])),
        'dataOlmStart': (new Date(json['dataOlmStart'])),
        'dataOlmSfarsit': (new Date(json['dataOlmSfarsit'])),
        'agent': json['agent'],
        'cuiFirma': json['cuiFirma'],
        'idCor': json['idCor'],
        'adresaLocMunca': json['adresaLocMunca'],
        'nrLocMunca': json['nrLocMunca'],
        'stare': OlmStareEnumFromJSON(json['stare']),
    };
}

export function OlmDTOToJSON(value?: OlmDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'dataOlm': (value.dataOlm.toISOString()),
        'dataOlmStart': (value.dataOlmStart.toISOString()),
        'dataOlmSfarsit': (value.dataOlmSfarsit.toISOString()),
        'agent': value.agent,
        'cuiFirma': value.cuiFirma,
        'idCor': value.idCor,
        'adresaLocMunca': value.adresaLocMunca,
        'nrLocMunca': value.nrLocMunca,
        'stare': OlmStareEnumToJSON(value.stare),
    };
}

