/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OlmDTOPagedResponse } from './OlmDTOPagedResponse';
import {
    OlmDTOPagedResponseFromJSON,
    OlmDTOPagedResponseFromJSONTyped,
    OlmDTOPagedResponseToJSON,
} from './OlmDTOPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface OlmDTOPagedResponseRequestResponse
 */
export interface OlmDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {OlmDTOPagedResponse}
     * @memberof OlmDTOPagedResponseRequestResponse
     */
    response: OlmDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof OlmDTOPagedResponseRequestResponse
     */
    errorMessage: ErrorMessage;
}

/**
 * Check if a given object implements the OlmDTOPagedResponseRequestResponse interface.
 */
export function instanceOfOlmDTOPagedResponseRequestResponse(value: object): value is OlmDTOPagedResponseRequestResponse {
    if (!('response' in value) || value['response'] === undefined) return false;
    if (!('errorMessage' in value) || value['errorMessage'] === undefined) return false;
    return true;
}

export function OlmDTOPagedResponseRequestResponseFromJSON(json: any): OlmDTOPagedResponseRequestResponse {
    return OlmDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function OlmDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OlmDTOPagedResponseRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': OlmDTOPagedResponseFromJSON(json['response']),
        'errorMessage': ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function OlmDTOPagedResponseRequestResponseToJSON(value?: OlmDTOPagedResponseRequestResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'response': OlmDTOPagedResponseToJSON(value['response']),
        'errorMessage': ErrorMessageToJSON(value['errorMessage']),
    };
}

