/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OlmDTO } from './OlmDTO';
import {
    OlmDTOFromJSON,
    OlmDTOFromJSONTyped,
    OlmDTOToJSON,
} from './OlmDTO';

/**
 * 
 * @export
 * @interface OlmDTOPagedResponse
 */
export interface OlmDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof OlmDTOPagedResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof OlmDTOPagedResponse
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof OlmDTOPagedResponse
     */
    totalCount: number;
    /**
     * 
     * @type {Array<OlmDTO>}
     * @memberof OlmDTOPagedResponse
     */
    data: Array<OlmDTO>;
}

/**
 * Check if a given object implements the OlmDTOPagedResponse interface.
 */
export function instanceOfOlmDTOPagedResponse(value: object): value is OlmDTOPagedResponse {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function OlmDTOPagedResponseFromJSON(json: any): OlmDTOPagedResponse {
    return OlmDTOPagedResponseFromJSONTyped(json, false);
}

export function OlmDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OlmDTOPagedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(OlmDTOFromJSON)),
    };
}

export function OlmDTOPagedResponseToJSON(value?: OlmDTOPagedResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'data': ((value['data'] as Array<any>).map(OlmDTOToJSON)),
    };
}

