/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const OlmStareEnum = {
    Activ: 'Activ',
    Expirat: 'Expirat'
} as const;
export type OlmStareEnum = typeof OlmStareEnum[keyof typeof OlmStareEnum];


export function instanceOfOlmStareEnum(value: any): boolean {
    for (const key in OlmStareEnum) {
        if (Object.prototype.hasOwnProperty.call(OlmStareEnum, key)) {
            if ((OlmStareEnum as Record<string, OlmStareEnum>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OlmStareEnumFromJSON(json: any): OlmStareEnum {
    return OlmStareEnumFromJSONTyped(json, false);
}

export function OlmStareEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): OlmStareEnum {
    return json as OlmStareEnum;
}

export function OlmStareEnumToJSON(value?: OlmStareEnum | null): any {
    return value as any;
}

