/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OlmStareEnum } from './OlmStareEnum';
import {
    OlmStareEnumFromJSON,
    OlmStareEnumFromJSONTyped,
    OlmStareEnumToJSON,
} from './OlmStareEnum';

/**
 * 
 * @export
 * @interface OlmUpdateDTO
 */
export interface OlmUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof OlmUpdateDTO
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof OlmUpdateDTO
     */
    dataOlm: Date;
    /**
     * 
     * @type {Date}
     * @memberof OlmUpdateDTO
     */
    dataOlmStart: Date;
    /**
     * 
     * @type {Date}
     * @memberof OlmUpdateDTO
     */
    dataOlmSfarsit: Date;
    /**
     * 
     * @type {string}
     * @memberof OlmUpdateDTO
     */
    agent: string;
    /**
     * 
     * @type {string}
     * @memberof OlmUpdateDTO
     */
    cuiFirma: string;
    /**
     * 
     * @type {string}
     * @memberof OlmUpdateDTO
     */
    idCor: string;
    /**
     * 
     * @type {string}
     * @memberof OlmUpdateDTO
     */
    adresaLocMunca: string;
    /**
     * 
     * @type {number}
     * @memberof OlmUpdateDTO
     */
    nrLocMunca: number;
    /**
     * 
     * @type {OlmStareEnum}
     * @memberof OlmUpdateDTO
     */
    stare: OlmStareEnum;
}

/**
 * Check if a given object implements the OlmUpdateDTO interface.
 */
export function instanceOfOlmUpdateDTO(value: object): value is OlmUpdateDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('dataOlm' in value) || value['dataOlm'] === undefined) return false;
    if (!('dataOlmStart' in value) || value['dataOlmStart'] === undefined) return false;
    if (!('dataOlmSfarsit' in value) || value['dataOlmSfarsit'] === undefined) return false;
    if (!('agent' in value) || value['agent'] === undefined) return false;
    if (!('cuiFirma' in value) || value['cuiFirma'] === undefined) return false;
    if (!('idCor' in value) || value['idCor'] === undefined) return false;
    if (!('adresaLocMunca' in value) || value['adresaLocMunca'] === undefined) return false;
    if (!('nrLocMunca' in value) || value['nrLocMunca'] === undefined) return false;
    if (!('stare' in value) || value['stare'] === undefined) return false;
    return true;
}

export function OlmUpdateDTOFromJSON(json: any): OlmUpdateDTO {
    return OlmUpdateDTOFromJSONTyped(json, false);
}

export function OlmUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): OlmUpdateDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'dataOlm': (new Date(json['dataOlm'])),
        'dataOlmStart': (new Date(json['dataOlmStart'])),
        'dataOlmSfarsit': (new Date(json['dataOlmSfarsit'])),
        'agent': json['agent'],
        'cuiFirma': json['cuiFirma'],
        'idCor': json['idCor'],
        'adresaLocMunca': json['adresaLocMunca'],
        'nrLocMunca': json['nrLocMunca'],
        'stare': OlmStareEnumFromJSON(json['stare']),
    };
}

export function OlmUpdateDTOToJSON(value?: OlmUpdateDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'dataOlm': ((value['dataOlm']).toISOString()),
        'dataOlmStart': ((value['dataOlmStart']).toISOString()),
        'dataOlmSfarsit': ((value['dataOlmSfarsit']).toISOString()),
        'agent': value['agent'],
        'cuiFirma': value['cuiFirma'],
        'idCor': value['idCor'],
        'adresaLocMunca': value['adresaLocMunca'],
        'nrLocMunca': value['nrLocMunca'],
        'stare': OlmStareEnumToJSON(value['stare']),
    };
}

