/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { RepartitiiDTOPagedResponse } from './RepartitiiDTOPagedResponse';
import {
    RepartitiiDTOPagedResponseFromJSON,
    RepartitiiDTOPagedResponseFromJSONTyped,
    RepartitiiDTOPagedResponseToJSON,
} from './RepartitiiDTOPagedResponse';

/**
 * 
 * @export
 * @interface RepartitiiDTOPagedResponseRequestResponse
 */
export interface RepartitiiDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {RepartitiiDTOPagedResponse}
     * @memberof RepartitiiDTOPagedResponseRequestResponse
     */
    response: RepartitiiDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof RepartitiiDTOPagedResponseRequestResponse
     */
    errorMessage: ErrorMessage;
}

/**
 * Check if a given object implements the RepartitiiDTOPagedResponseRequestResponse interface.
 */
export function instanceOfRepartitiiDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "response" in value;
    isInstance = isInstance && "errorMessage" in value;

    return isInstance;
}

export function RepartitiiDTOPagedResponseRequestResponseFromJSON(json: any): RepartitiiDTOPagedResponseRequestResponse {
    return RepartitiiDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function RepartitiiDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepartitiiDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': RepartitiiDTOPagedResponseFromJSON(json['response']),
        'errorMessage': ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function RepartitiiDTOPagedResponseRequestResponseToJSON(value?: RepartitiiDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': RepartitiiDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

