/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RepartitiiDTO } from './RepartitiiDTO';
import {
    RepartitiiDTOFromJSON,
    RepartitiiDTOFromJSONTyped,
    RepartitiiDTOToJSON,
} from './RepartitiiDTO';

/**
 * 
 * @export
 * @interface RepartitiiDTOPagedResponse
 */
export interface RepartitiiDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof RepartitiiDTOPagedResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof RepartitiiDTOPagedResponse
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof RepartitiiDTOPagedResponse
     */
    totalCount: number;
    /**
     * 
     * @type {Array<RepartitiiDTO>}
     * @memberof RepartitiiDTOPagedResponse
     */
    data: Array<RepartitiiDTO>;
}

/**
 * Check if a given object implements the RepartitiiDTOPagedResponse interface.
 */
export function instanceOfRepartitiiDTOPagedResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "page" in value;
    isInstance = isInstance && "pageSize" in value;
    isInstance = isInstance && "totalCount" in value;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function RepartitiiDTOPagedResponseFromJSON(json: any): RepartitiiDTOPagedResponse {
    return RepartitiiDTOPagedResponseFromJSONTyped(json, false);
}

export function RepartitiiDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepartitiiDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(RepartitiiDTOFromJSON)),
    };
}

export function RepartitiiDTOPagedResponseToJSON(value?: RepartitiiDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': ((value.data as Array<any>).map(RepartitiiDTOToJSON)),
    };
}

