/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RepartitiiDTOPagedResponse } from './RepartitiiDTOPagedResponse';
import {
    RepartitiiDTOPagedResponseFromJSON,
    RepartitiiDTOPagedResponseFromJSONTyped,
    RepartitiiDTOPagedResponseToJSON,
} from './RepartitiiDTOPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface RepartitiiDTOPagedResponseRequestResponse
 */
export interface RepartitiiDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {RepartitiiDTOPagedResponse}
     * @memberof RepartitiiDTOPagedResponseRequestResponse
     */
    response: RepartitiiDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof RepartitiiDTOPagedResponseRequestResponse
     */
    errorMessage: ErrorMessage;
}

/**
 * Check if a given object implements the RepartitiiDTOPagedResponseRequestResponse interface.
 */
export function instanceOfRepartitiiDTOPagedResponseRequestResponse(value: object): value is RepartitiiDTOPagedResponseRequestResponse {
    if (!('response' in value) || value['response'] === undefined) return false;
    if (!('errorMessage' in value) || value['errorMessage'] === undefined) return false;
    return true;
}

export function RepartitiiDTOPagedResponseRequestResponseFromJSON(json: any): RepartitiiDTOPagedResponseRequestResponse {
    return RepartitiiDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function RepartitiiDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepartitiiDTOPagedResponseRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': RepartitiiDTOPagedResponseFromJSON(json['response']),
        'errorMessage': ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function RepartitiiDTOPagedResponseRequestResponseToJSON(value?: RepartitiiDTOPagedResponseRequestResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'response': RepartitiiDTOPagedResponseToJSON(value['response']),
        'errorMessage': ErrorMessageToJSON(value['errorMessage']),
    };
}

