/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RezultatRepartitieEnum } from './RezultatRepartitieEnum';
import {
    RezultatRepartitieEnumFromJSON,
    RezultatRepartitieEnumFromJSONTyped,
    RezultatRepartitieEnumToJSON,
} from './RezultatRepartitieEnum';

/**
 * 
 * @export
 * @interface RepartitiiAddDTO
 */
export interface RepartitiiAddDTO {
    /**
     * 
     * @type {string}
     * @memberof RepartitiiAddDTO
     */
    cnp?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof RepartitiiAddDTO
     */
    dataRepartitie: Date;
    /**
     * 
     * @type {string}
     * @memberof RepartitiiAddDTO
     */
    idOlm: string;
    /**
     * 
     * @type {RezultatRepartitieEnum}
     * @memberof RepartitiiAddDTO
     */
    rezultat: RezultatRepartitieEnum;
    /**
     * 
     * @type {string}
     * @memberof RepartitiiAddDTO
     */
    userId: string;
}

/**
 * Check if a given object implements the RepartitiiAddDTO interface.
 */
export function instanceOfRepartitiiAddDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "dataRepartitie" in value;
    isInstance = isInstance && "idOlm" in value;
    isInstance = isInstance && "rezultat" in value;
    isInstance = isInstance && "userId" in value;

    return isInstance;
}

export function RepartitiiAddDTOFromJSON(json: any): RepartitiiAddDTO {
    return RepartitiiAddDTOFromJSONTyped(json, false);
}

export function RepartitiiAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RepartitiiAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cnp': !exists(json, 'cnp') ? undefined : json['cnp'],
        'dataRepartitie': (new Date(json['dataRepartitie'])),
        'idOlm': json['idOlm'],
        'rezultat': RezultatRepartitieEnumFromJSON(json['rezultat']),
        'userId': json['userId'],
    };
}

export function RepartitiiAddDTOToJSON(value?: RepartitiiAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cnp': value.cnp,
        'dataRepartitie': (value.dataRepartitie.toISOString()),
        'idOlm': value.idOlm,
        'rezultat': RezultatRepartitieEnumToJSON(value.rezultat),
        'userId': value.userId,
    };
}

