/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const RezultatRepartitieEnum = {
    Acceptat: 'Acceptat',
    Respins: 'Respins'
} as const;
export type RezultatRepartitieEnum = typeof RezultatRepartitieEnum[keyof typeof RezultatRepartitieEnum];


export function instanceOfRezultatRepartitieEnum(value: any): boolean {
    for (const key in RezultatRepartitieEnum) {
        if (Object.prototype.hasOwnProperty.call(RezultatRepartitieEnum, key)) {
            if ((RezultatRepartitieEnum as Record<string, RezultatRepartitieEnum>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RezultatRepartitieEnumFromJSON(json: any): RezultatRepartitieEnum {
    return RezultatRepartitieEnumFromJSONTyped(json, false);
}

export function RezultatRepartitieEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): RezultatRepartitieEnum {
    return json as RezultatRepartitieEnum;
}

export function RezultatRepartitieEnumToJSON(value?: RezultatRepartitieEnum | null): any {
    return value as any;
}

