/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SolicitantiDTO } from './SolicitantiDTO';
import {
    SolicitantiDTOFromJSON,
    SolicitantiDTOFromJSONTyped,
    SolicitantiDTOToJSON,
} from './SolicitantiDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface SolicitantiDTORequestResponse
 */
export interface SolicitantiDTORequestResponse {
    /**
     * 
     * @type {SolicitantiDTO}
     * @memberof SolicitantiDTORequestResponse
     */
    response: SolicitantiDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof SolicitantiDTORequestResponse
     */
    errorMessage: ErrorMessage;
}

/**
 * Check if a given object implements the SolicitantiDTORequestResponse interface.
 */
export function instanceOfSolicitantiDTORequestResponse(value: object): value is SolicitantiDTORequestResponse {
    if (!('response' in value) || value['response'] === undefined) return false;
    if (!('errorMessage' in value) || value['errorMessage'] === undefined) return false;
    return true;
}

export function SolicitantiDTORequestResponseFromJSON(json: any): SolicitantiDTORequestResponse {
    return SolicitantiDTORequestResponseFromJSONTyped(json, false);
}

export function SolicitantiDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SolicitantiDTORequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': SolicitantiDTOFromJSON(json['response']),
        'errorMessage': ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function SolicitantiDTORequestResponseToJSON(value?: SolicitantiDTORequestResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'response': SolicitantiDTOToJSON(value['response']),
        'errorMessage': ErrorMessageToJSON(value['errorMessage']),
    };
}

