/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SolicitantiDTO } from './SolicitantiDTO';
import {
    SolicitantiDTOFromJSON,
    SolicitantiDTOFromJSONTyped,
    SolicitantiDTOToJSON,
} from './SolicitantiDTO';

/**
 * 
 * @export
 * @interface SolicitantiDTOPagedResponse
 */
export interface SolicitantiDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof SolicitantiDTOPagedResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof SolicitantiDTOPagedResponse
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof SolicitantiDTOPagedResponse
     */
    totalCount: number;
    /**
     * 
     * @type {Array<SolicitantiDTO>}
     * @memberof SolicitantiDTOPagedResponse
     */
    data: Array<SolicitantiDTO>;
}

/**
 * Check if a given object implements the SolicitantiDTOPagedResponse interface.
 */
export function instanceOfSolicitantiDTOPagedResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "page" in value;
    isInstance = isInstance && "pageSize" in value;
    isInstance = isInstance && "totalCount" in value;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function SolicitantiDTOPagedResponseFromJSON(json: any): SolicitantiDTOPagedResponse {
    return SolicitantiDTOPagedResponseFromJSONTyped(json, false);
}

export function SolicitantiDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SolicitantiDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(SolicitantiDTOFromJSON)),
    };
}

export function SolicitantiDTOPagedResponseToJSON(value?: SolicitantiDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': ((value.data as Array<any>).map(SolicitantiDTOToJSON)),
    };
}

