/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SolicitantiDTO } from './SolicitantiDTO';
import {
    SolicitantiDTOFromJSON,
    SolicitantiDTOFromJSONTyped,
    SolicitantiDTOToJSON,
} from './SolicitantiDTO';

/**
 * 
 * @export
 * @interface SolicitantiDTOPagedResponse
 */
export interface SolicitantiDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof SolicitantiDTOPagedResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof SolicitantiDTOPagedResponse
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof SolicitantiDTOPagedResponse
     */
    totalCount: number;
    /**
     * 
     * @type {Array<SolicitantiDTO>}
     * @memberof SolicitantiDTOPagedResponse
     */
    data: Array<SolicitantiDTO>;
}

/**
 * Check if a given object implements the SolicitantiDTOPagedResponse interface.
 */
export function instanceOfSolicitantiDTOPagedResponse(value: object): value is SolicitantiDTOPagedResponse {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function SolicitantiDTOPagedResponseFromJSON(json: any): SolicitantiDTOPagedResponse {
    return SolicitantiDTOPagedResponseFromJSONTyped(json, false);
}

export function SolicitantiDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SolicitantiDTOPagedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(SolicitantiDTOFromJSON)),
    };
}

export function SolicitantiDTOPagedResponseToJSON(value?: SolicitantiDTOPagedResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'data': ((value['data'] as Array<any>).map(SolicitantiDTOToJSON)),
    };
}

