/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SolicitantiDTO
 */
export interface SolicitantiDTO {
    /**
     * 
     * @type {string}
     * @memberof SolicitantiDTO
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof SolicitantiDTO
     */
    dataInregistare: Date;
    /**
     * 
     * @type {string}
     * @memberof SolicitantiDTO
     */
    cnpSolicitant: string;
    /**
     * 
     * @type {string}
     * @memberof SolicitantiDTO
     */
    nume: string;
    /**
     * 
     * @type {string}
     * @memberof SolicitantiDTO
     */
    prenume: string;
    /**
     * 
     * @type {string}
     * @memberof SolicitantiDTO
     */
    adresa?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SolicitantiDTO
     */
    userId: string;
}

/**
 * Check if a given object implements the SolicitantiDTO interface.
 */
export function instanceOfSolicitantiDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "dataInregistare" in value;
    isInstance = isInstance && "cnpSolicitant" in value;
    isInstance = isInstance && "nume" in value;
    isInstance = isInstance && "prenume" in value;
    isInstance = isInstance && "userId" in value;

    return isInstance;
}

export function SolicitantiDTOFromJSON(json: any): SolicitantiDTO {
    return SolicitantiDTOFromJSONTyped(json, false);
}

export function SolicitantiDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SolicitantiDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'dataInregistare': (new Date(json['dataInregistare'])),
        'cnpSolicitant': json['cnpSolicitant'],
        'nume': json['nume'],
        'prenume': json['prenume'],
        'adresa': !exists(json, 'adresa') ? undefined : json['adresa'],
        'userId': json['userId'],
    };
}

export function SolicitantiDTOToJSON(value?: SolicitantiDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'dataInregistare': (value.dataInregistare.toISOString()),
        'cnpSolicitant': value.cnpSolicitant,
        'nume': value.nume,
        'prenume': value.prenume,
        'adresa': value.adresa,
        'userId': value.userId,
    };
}

