/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SolicitantiUpdateDTO
 */
export interface SolicitantiUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof SolicitantiUpdateDTO
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof SolicitantiUpdateDTO
     */
    dataInregistare: Date;
    /**
     * 
     * @type {string}
     * @memberof SolicitantiUpdateDTO
     */
    nume: string;
    /**
     * 
     * @type {string}
     * @memberof SolicitantiUpdateDTO
     */
    prenume: string;
    /**
     * 
     * @type {string}
     * @memberof SolicitantiUpdateDTO
     */
    adresa?: string | null;
}

/**
 * Check if a given object implements the SolicitantiUpdateDTO interface.
 */
export function instanceOfSolicitantiUpdateDTO(value: object): value is SolicitantiUpdateDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('dataInregistare' in value) || value['dataInregistare'] === undefined) return false;
    if (!('nume' in value) || value['nume'] === undefined) return false;
    if (!('prenume' in value) || value['prenume'] === undefined) return false;
    return true;
}

export function SolicitantiUpdateDTOFromJSON(json: any): SolicitantiUpdateDTO {
    return SolicitantiUpdateDTOFromJSONTyped(json, false);
}

export function SolicitantiUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SolicitantiUpdateDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'dataInregistare': (new Date(json['dataInregistare'])),
        'nume': json['nume'],
        'prenume': json['prenume'],
        'adresa': json['adresa'] == null ? undefined : json['adresa'],
    };
}

export function SolicitantiUpdateDTOToJSON(value?: SolicitantiUpdateDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'dataInregistare': ((value['dataInregistare']).toISOString()),
        'nume': value['nume'],
        'prenume': value['prenume'],
        'adresa': value['adresa'],
    };
}

