/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { SolicitantiDTOPagedResponse } from './SolicitantiDTOPagedResponse';
import {
    SolicitantiDTOPagedResponseFromJSON,
    SolicitantiDTOPagedResponseFromJSONTyped,
    SolicitantiDTOPagedResponseToJSON,
} from './SolicitantiDTOPagedResponse';

/**
 * 
 * @export
 * @interface SolicitantiDTOPagedResponseRequestResponse
 */
export interface SolicitantiDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {SolicitantiDTOPagedResponse}
     * @memberof SolicitantiDTOPagedResponseRequestResponse
     */
    response: SolicitantiDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof SolicitantiDTOPagedResponseRequestResponse
     */
    errorMessage: ErrorMessage;
}

/**
 * Check if a given object implements the SolicitantiDTOPagedResponseRequestResponse interface.
 */
export function instanceOfSolicitantiDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "response" in value;
    isInstance = isInstance && "errorMessage" in value;

    return isInstance;
}

export function SolicitantiDTOPagedResponseRequestResponseFromJSON(json: any): SolicitantiDTOPagedResponseRequestResponse {
    return SolicitantiDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function SolicitantiDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SolicitantiDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': SolicitantiDTOPagedResponseFromJSON(json['response']),
        'errorMessage': ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function SolicitantiDTOPagedResponseRequestResponseToJSON(value?: SolicitantiDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': SolicitantiDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

