/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SolicitantiUpdateDTO
 */
export interface SolicitantiUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof SolicitantiUpdateDTO
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof SolicitantiUpdateDTO
     */
    dataInregistare: Date;
    /**
     * 
     * @type {string}
     * @memberof SolicitantiUpdateDTO
     */
    nume: string;
    /**
     * 
     * @type {string}
     * @memberof SolicitantiUpdateDTO
     */
    prenume: string;
    /**
     * 
     * @type {string}
     * @memberof SolicitantiUpdateDTO
     */
    adresa?: string | null;
}

/**
 * Check if a given object implements the SolicitantiUpdateDTO interface.
 */
export function instanceOfSolicitantiUpdateDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "dataInregistare" in value;
    isInstance = isInstance && "nume" in value;
    isInstance = isInstance && "prenume" in value;

    return isInstance;
}

export function SolicitantiUpdateDTOFromJSON(json: any): SolicitantiUpdateDTO {
    return SolicitantiUpdateDTOFromJSONTyped(json, false);
}

export function SolicitantiUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SolicitantiUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'dataInregistare': (new Date(json['dataInregistare'])),
        'nume': json['nume'],
        'prenume': json['prenume'],
        'adresa': !exists(json, 'adresa') ? undefined : json['adresa'],
    };
}

export function SolicitantiUpdateDTOToJSON(value?: SolicitantiUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'dataInregistare': (value.dataInregistare.toISOString()),
        'nume': value.nume,
        'prenume': value.prenume,
        'adresa': value.adresa,
    };
}

