/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StudiiAddDTO
 */
export interface StudiiAddDTO {
    /**
     * 
     * @type {string}
     * @memberof StudiiAddDTO
     */
    denStudii: string;
}

/**
 * Check if a given object implements the StudiiAddDTO interface.
 */
export function instanceOfStudiiAddDTO(value: object): value is StudiiAddDTO {
    if (!('denStudii' in value) || value['denStudii'] === undefined) return false;
    return true;
}

export function StudiiAddDTOFromJSON(json: any): StudiiAddDTO {
    return StudiiAddDTOFromJSONTyped(json, false);
}

export function StudiiAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudiiAddDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'denStudii': json['denStudii'],
    };
}

export function StudiiAddDTOToJSON(value?: StudiiAddDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'denStudii': value['denStudii'],
    };
}

