/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StudiiDTOPagedResponse } from './StudiiDTOPagedResponse';
import {
    StudiiDTOPagedResponseFromJSON,
    StudiiDTOPagedResponseFromJSONTyped,
    StudiiDTOPagedResponseToJSON,
} from './StudiiDTOPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface StudiiDTOPagedResponseRequestResponse
 */
export interface StudiiDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {StudiiDTOPagedResponse}
     * @memberof StudiiDTOPagedResponseRequestResponse
     */
    response: StudiiDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof StudiiDTOPagedResponseRequestResponse
     */
    errorMessage: ErrorMessage;
}

/**
 * Check if a given object implements the StudiiDTOPagedResponseRequestResponse interface.
 */
export function instanceOfStudiiDTOPagedResponseRequestResponse(value: object): value is StudiiDTOPagedResponseRequestResponse {
    if (!('response' in value) || value['response'] === undefined) return false;
    if (!('errorMessage' in value) || value['errorMessage'] === undefined) return false;
    return true;
}

export function StudiiDTOPagedResponseRequestResponseFromJSON(json: any): StudiiDTOPagedResponseRequestResponse {
    return StudiiDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function StudiiDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudiiDTOPagedResponseRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': StudiiDTOPagedResponseFromJSON(json['response']),
        'errorMessage': ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function StudiiDTOPagedResponseRequestResponseToJSON(value?: StudiiDTOPagedResponseRequestResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'response': StudiiDTOPagedResponseToJSON(value['response']),
        'errorMessage': ErrorMessageToJSON(value['errorMessage']),
    };
}

