/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StudiiDTO } from './StudiiDTO';
import {
    StudiiDTOFromJSON,
    StudiiDTOFromJSONTyped,
    StudiiDTOToJSON,
} from './StudiiDTO';

/**
 * 
 * @export
 * @interface StudiiDTOPagedResponse
 */
export interface StudiiDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof StudiiDTOPagedResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof StudiiDTOPagedResponse
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof StudiiDTOPagedResponse
     */
    totalCount: number;
    /**
     * 
     * @type {Array<StudiiDTO>}
     * @memberof StudiiDTOPagedResponse
     */
    data: Array<StudiiDTO>;
}

/**
 * Check if a given object implements the StudiiDTOPagedResponse interface.
 */
export function instanceOfStudiiDTOPagedResponse(value: object): value is StudiiDTOPagedResponse {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function StudiiDTOPagedResponseFromJSON(json: any): StudiiDTOPagedResponse {
    return StudiiDTOPagedResponseFromJSONTyped(json, false);
}

export function StudiiDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudiiDTOPagedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(StudiiDTOFromJSON)),
    };
}

export function StudiiDTOPagedResponseToJSON(value?: StudiiDTOPagedResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'data': ((value['data'] as Array<any>).map(StudiiDTOToJSON)),
    };
}

