/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { StudiiDTO } from './StudiiDTO';
import {
    StudiiDTOFromJSON,
    StudiiDTOFromJSONTyped,
    StudiiDTOToJSON,
} from './StudiiDTO';

/**
 * 
 * @export
 * @interface StudiiDTORequestResponse
 */
export interface StudiiDTORequestResponse {
    /**
     * 
     * @type {StudiiDTO}
     * @memberof StudiiDTORequestResponse
     */
    response: StudiiDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof StudiiDTORequestResponse
     */
    errorMessage: ErrorMessage;
}

/**
 * Check if a given object implements the StudiiDTORequestResponse interface.
 */
export function instanceOfStudiiDTORequestResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "response" in value;
    isInstance = isInstance && "errorMessage" in value;

    return isInstance;
}

export function StudiiDTORequestResponseFromJSON(json: any): StudiiDTORequestResponse {
    return StudiiDTORequestResponseFromJSONTyped(json, false);
}

export function StudiiDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudiiDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': StudiiDTOFromJSON(json['response']),
        'errorMessage': ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function StudiiDTORequestResponseToJSON(value?: StudiiDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': StudiiDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

