/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StudiiDTO } from './StudiiDTO';
import {
    StudiiDTOFromJSON,
    StudiiDTOFromJSONTyped,
    StudiiDTOToJSON,
} from './StudiiDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface StudiiDTORequestResponse
 */
export interface StudiiDTORequestResponse {
    /**
     * 
     * @type {StudiiDTO}
     * @memberof StudiiDTORequestResponse
     */
    response: StudiiDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof StudiiDTORequestResponse
     */
    errorMessage: ErrorMessage;
}

/**
 * Check if a given object implements the StudiiDTORequestResponse interface.
 */
export function instanceOfStudiiDTORequestResponse(value: object): value is StudiiDTORequestResponse {
    if (!('response' in value) || value['response'] === undefined) return false;
    if (!('errorMessage' in value) || value['errorMessage'] === undefined) return false;
    return true;
}

export function StudiiDTORequestResponseFromJSON(json: any): StudiiDTORequestResponse {
    return StudiiDTORequestResponseFromJSONTyped(json, false);
}

export function StudiiDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudiiDTORequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': StudiiDTOFromJSON(json['response']),
        'errorMessage': ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function StudiiDTORequestResponseToJSON(value?: StudiiDTORequestResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'response': StudiiDTOToJSON(value['response']),
        'errorMessage': ErrorMessageToJSON(value['errorMessage']),
    };
}

