/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StudiiUpdateDTO
 */
export interface StudiiUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof StudiiUpdateDTO
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof StudiiUpdateDTO
     */
    denStudii: string;
}

/**
 * Check if a given object implements the StudiiUpdateDTO interface.
 */
export function instanceOfStudiiUpdateDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "denStudii" in value;

    return isInstance;
}

export function StudiiUpdateDTOFromJSON(json: any): StudiiUpdateDTO {
    return StudiiUpdateDTOFromJSONTyped(json, false);
}

export function StudiiUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudiiUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'denStudii': json['denStudii'],
    };
}

export function StudiiUpdateDTOToJSON(value?: StudiiUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'denStudii': value.denStudii,
    };
}

