/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StudiiUpdateDTO
 */
export interface StudiiUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof StudiiUpdateDTO
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof StudiiUpdateDTO
     */
    denStudii: string;
}

/**
 * Check if a given object implements the StudiiUpdateDTO interface.
 */
export function instanceOfStudiiUpdateDTO(value: object): value is StudiiUpdateDTO {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('denStudii' in value) || value['denStudii'] === undefined) return false;
    return true;
}

export function StudiiUpdateDTOFromJSON(json: any): StudiiUpdateDTO {
    return StudiiUpdateDTOFromJSONTyped(json, false);
}

export function StudiiUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudiiUpdateDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'denStudii': json['denStudii'],
    };
}

export function StudiiUpdateDTOToJSON(value?: StudiiUpdateDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'denStudii': value['denStudii'],
    };
}

