/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserDTO } from './UserDTO';
import {
    UserDTOFromJSON,
    UserDTOFromJSONTyped,
    UserDTOToJSON,
} from './UserDTO';

/**
 * 
 * @export
 * @interface UserDTOPagedResponse
 */
export interface UserDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof UserDTOPagedResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof UserDTOPagedResponse
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof UserDTOPagedResponse
     */
    totalCount: number;
    /**
     * 
     * @type {Array<UserDTO>}
     * @memberof UserDTOPagedResponse
     */
    data: Array<UserDTO>;
}

/**
 * Check if a given object implements the UserDTOPagedResponse interface.
 */
export function instanceOfUserDTOPagedResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "page" in value;
    isInstance = isInstance && "pageSize" in value;
    isInstance = isInstance && "totalCount" in value;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function UserDTOPagedResponseFromJSON(json: any): UserDTOPagedResponse {
    return UserDTOPagedResponseFromJSONTyped(json, false);
}

export function UserDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalCount': json['totalCount'],
        'data': ((json['data'] as Array<any>).map(UserDTOFromJSON)),
    };
}

export function UserDTOPagedResponseToJSON(value?: UserDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': ((value.data as Array<any>).map(UserDTOToJSON)),
    };
}

